length(grep("iconHomicideShooting", homicides))
length(grep("Shooting", homicides))
length(grep("iconHomicideShooting|icon_homicide_shooting", homicides))
length(grep("Cause: [Ss]hooting", homicides))
length(grep("Cause: shooting", homicides))
i <- grep("[Cc]ause: [Ss]hooting", homicides)
j <- grep("[Ss]hooting", homicides)
str(i)
nrow(grep("iconHomicideShooting", homicides))
length(grep("iconHomicideShooting", homicides))